---
title: "DS_TDM_Statistics"
output: html_document
---

```{r}
library(tidyr)
library(magrittr)
library(dplyr)
library(reshape2)
library(emmeans)
library(rstatix)
library(forcats)
library(purrr)
library(broom)
```

upload data
```{r}
C <- read.csv("C_chlor_tidy_ArenaOnly.csv")

```

Transform
```{r}
DM_96h <- C %>% 
  select(Treatment, Replicate, Minutes, Well, Label, DistanceMoved) %>% 
  unite(newID, Well, Replicate) %>%
  mutate(Treatment = fct_relevel(Treatment, "Vehicle", "Low", "Medium", "High"),
         Treatment= fct_recode(Treatment, "0" = "Vehicle", 
                               "0.05" = "Low", 
                               "0.5" = "Medium", 
                               "5" = "High"), 
         Label = fct_relevel(Label, "Dark1", "Light1", "Dark2", "Light2", "Dark3")) %>% 
  group_by(Treatment, newID, Label) %>% 
  summarize(MeanDM = mean(DistanceMoved))
View(DM_96h)

```


C
```{r}
#SHAPIRO
C_shapiro <- DM_96h %>%
  group_by(Label) %>%
  nest() %>% 
  ungroup() %>% 
  mutate(shapiro = map(data, ~tidy(shapiro.test(.x$MeanDM)))) %>% 
  unnest(shapiro) %>% 
  select(Label, statistic, p.value, method)
  View(C_shapiro)


#LEVENES- TEST FOR HOMOGENEITY OF VARIANCE
C_levene <- DM_96h %>%
  group_by(Label) %>%
  nest() %>% 
  mutate(levene = map(data, ~levene_test(.x, MeanDM ~ Treatment))) %>% 
  unnest(levene) %>% 
  select(Label, df1, df2, statistic, p)
View(C_levene)

#KRUSKALL
C_KRUSKAL <- DM_96h %>%
  group_by(Label) %>%
  nest() %>% 
  mutate(kruskal = map(data, ~kruskal_test(.x, MeanDM ~ Treatment))) %>% 
  unnest(kruskal) 
View(C_KRUSKAL)

#DUNN'S
C_DUNNS <- DM_96h %>%
  group_by(Label) %>%
  nest() %>% 
  mutate(dunns = map(data, ~dunn_test(.x, MeanDM ~ Treatment, p.adjust.method = "bonferroni"))) %>% 
  unnest(dunns)
View(C_DUNNS)


#DUNNET- TRT V CTRL
C_dunnetx <- DM_96h %>% 
  group_by(Label) %>% 
  nest() %>% 
  mutate(dunnetx = map(data, 
                   ~tidy(contrast(emmeans((ref_grid(lm(MeanDM ~ Treatment, data=.x))),"Treatment"), method="trt.vs.ctrl")))) %>% 
  unnest(dunnetx) %>% 
  mutate(significant = case_when(p.value > 0.05 ~ "ns",
    p.value <= 0.05 ~"*", 
    p.value <= 0.01 ~"**"))

View(C_dunnetx)

#edit for exporting
C_DUNNETforprint <- C_dunnetx %>% 
  select(Label, level1, level2, estimate, std.error, df, statistic, p.value, significant) %>% 
  ungroup()
View(C_DUNNETforprint)

#Export
write.table(C_DUNNETforprint, "CH_96h_dunnetx.txt", 
            sep = "\t", quote = F, row.names = F)

```

